services:
  backend:
    build: ./backend
    container_name: event-sync-backend
    ports:
      - "8081:8080"
    expose:
      - "8080"

  frontend:
    build: ./frontend
    container_name: event-sync-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
